export enum ERRORS {
    NO_IDENTIFIER_FOUND = "No container found for The logged identifier. Maybe there is no identifier with that name or it was not corretly rendered",
    NO_NAME_OR_EXTENSION_PROVIDED = "Missing name or extension",
    NO_NAME_OR_PORJECT_TYPE_PROVIDED = "Missing name or project type",
    NO_BLOCK_NAME_PROVIDED = "Missing block name",
    NO_PATH_PROVIDED = "Missing Path",
    NO_VALID_EXTENSION = "Invalid extension",
    NO_VALID_PROJECT_TYPE = "Invalid project type",
    NO_VALID_FORM_ELEMENT = "The passed element is not a valid form element or it is not yet aviable for be readed in the function",
    NO_CURRENT_PROJECT = "Cannot retrive the current project",
    NO_FOLDER_PASSED = "The current passed path is not of a folder",
    MISSING_FIELDS = "Some fields are empty or missing",
    EMPTY_BLOCK_NAME = "Missing block name",
    PROJECT_ALREADY_PRESENT = "A project with the same name is already present",
}